# This is a basic workflow to help you get started with Actions

name: Download file

# Controls when the workflow will run
on:
  workflow_dispatch:
  # schedule:
  # - cron:  0 0 */1 * * #Run every alertnate day
  
jobs:
  download-file:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Download file using selenium
        #Install Selenium WebDriver

        run: |
          curl -X  GET "https://api.cloudflare.com/client/v4/radar/datasets/ranking_top_1000000" \-H "X-Auth-Email: shiv4124@gmail.com" \-H "X-Auth-Key: 27f7d365862438ffa6655ad14a77feb3a9ff4" -o file.txt

      - name: Update file content
      # - uses: actions/checkout@v4
        run: |
          sed -i '/^domain$/d' file.txt
          cat file.txt > test_domain.txt
        # with : 
        #   name: "file.txt"
        #   path: "https://github.com/ExabeamLabs/ExabeamTIS/blob/main/"

      - name: commit and push file to repository
        run: |
          git config --global user.name "shivanand-nehatrao-exa"
          git config --global user.email "shivanand.nehatrao@exabeam.com"
          git add test_domain.txt
          git checkout file.txt
          git commit -m "uploaded latest ranked domain file"
          git push
