# This is a basic workflow to help you get started with Actions

name: Download file

# Controls when the workflow will run
on:
  workflow_dispatch:
  # schedule:
  # - cron:  0 0 */1 * * #Run every alertnate day
  
jobs:
  download-file:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Download file using selenium
        #Install Selenium WebDriver

        run: |
          # pip install selenium
          # from selenium import Webdriver
          # from selenium.webdriver.common.by
          # import By from selenium.webdriver.support.ui
          # import WebDriverWait from selenium,webdriver.support
          # import expected_condiitons as EC

          # options = webdriver.ChromeOptions()
          # options.add_argument('headless')

          driver = webdriver.Chrome(options=options)
          # driver.get('https://radar.cloudflare.com/charts/LargerTopDomainsTable/attachment?id=1257&top=1000000')

          # checkbox = WebDriverWait(driver, 10).until(_clickable((By.CSS_SELECTOR, '#checkbox-id')))

          # checkbox.click()

          # file_link = WebDriverWait(driver, 10).until(_clickable((By.CSS_SELECTOR, '#file-link-id')))

          #Download the file 

          # file_url = file_link.get_attribute('href')
          curl -o file.txt "https://radar.cloudflare.com/charts/LargerTopDomainsTable/attachment?id=1257&top=1000000"

          # driver.quit()

      - name: Update file content
      # - uses: actions/checkout@v4
        run: |
          cat file.txt > is_ranked_domain.txt
        # with : 
        #   name: "file.txt"
        #   path: "https://github.com/ExabeamLabs/ExabeamTIS/blob/main/"

      - name: commit and push file to repository
        run: |
          git config --global user.name "shivanand-nehatrao-exa"
          git config --global user.email "shivanand.nehatrao@exabeam.com"
          git add is_ranked_domain.txt
          git commit -m "uploaded latest ranked domain file"
          git push
